import React, { useState } from 'react';
import {
  View, Text, TextInput, Button, TouchableOpacity,
    StyleSheet, Alert
    } from 'react-native';
    import { saveUser } from './storage';

    const RegisterScreen = ({ navigation }) => {
      const [role, setRole] = useState('rider');
        const [name, setName] = useState('');
          const [phone, setPhone] = useState('');
            const [vehicleType, setVehicleType] = useState('');
              const [licensePlate, setLicensePlate] = useState('');
                const [password, setPassword] = useState('');
                  const [confirmPassword, setConfirmPassword] = useState('');

                    const handleRegister = async () => {
                        if (!name || !phone || !password || !confirmPassword) {
                              return Alert.alert('Error', 'Please fill in all required fields');
                                  }

                                      if (password !== confirmPassword) {
                                            return Alert.alert('Error', 'Passwords do not match');
                                                }

                                                    if (role === 'driver' && (!vehicleType || !licensePlate)) {
                                                          return Alert.alert('Error', 'Please enter vehicle details');
                                                              }

                                                                  const user = {
                                                                        name,
                                                                              phone,
                                                                                    password,
                                                                                          role,
                                                                                                vehicleType: role === 'driver' ? vehicleType : null,
                                                                                                      licensePlate: role === 'driver' ? licensePlate : null
                                                                                                          };

                                                                                                              await saveUser(user);
                                                                                                                  Alert.alert('Success', `Registered as ${role}`);
                                                                                                                      navigation.replace('Login');
                                                                                                                        };

                                                                                                                          return (
                                                                                                                              <View style={styles.container}>
                                                                                                                                    <Text style={styles.title}>Register as {role === 'driver' ? 'Driver' : 'Rider'}</Text>

                                                                                                                                          <View style={styles.toggleContainer}>
                                                                                                                                                  <TouchableOpacity
                                                                                                                                                            style={[styles.toggle, role === 'rider' && styles.active]}
                                                                                                                                                                      onPress={() => setRole('rider')}>
                                                                                                                                                                                <Text>Rider</Text>
                                                                                                                                                                                        </TouchableOpacity>
                                                                                                                                                                                                <TouchableOpacity
                                                                                                                                                                                                          style={[styles.toggle, role === 'driver' && styles.active]}
                                                                                                                                                                                                                    onPress={() => setRole('driver')}>
                                                                                                                                                                                                                              <Text>Driver</Text>
                                                                                                                                                                                                                                      </TouchableOpacity>
                                                                                                                                                                                                                                            </View>

                                                                                                                                                                                                                                                  <TextInput
                                                                                                                                                                                                                                                          style={styles.input}
                                                                                                                                                                                                                                                                  placeholder="Full Name"
                                                                                                                                                                                                                                                                          value={name}
                                                                                                                                                                                                                                                                                  onChangeText={setName}
                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                              <TextInput
                                                                                                                                                                                                                                                                                                      style={styles.input}
                                                                                                                                                                                                                                                                                                              placeholder="Phone Number"
                                                                                                                                                                                                                                                                                                                      keyboardType="phone-pad"
                                                                                                                                                                                                                                                                                                                              value={phone}
                                                                                                                                                                                                                                                                                                                                      onChangeText={setPhone}
                                                                                                                                                                                                                                                                                                                                            />

                                                                                                                                                                                                                                                                                                                                                  {role === 'driver' && (
                                                                                                                                                                                                                                                                                                                                                          <>
                                                                                                                                                                                                                                                                                                                                                                    <TextInput
                                                                                                                                                                                                                                                                                                                                                                                style={styles.input}
                                                                                                                                                                                                                                                                                                                                                                                            placeholder="Vehicle Type (e.g. Car or Bike)"
                                                                                                                                                                                                                                                                                                                                                                                                        value={vehicleType}
                                                                                                                                                                                                                                                                                                                                                                                                                    onChangeText={setVehicleType}
                                                                                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                                                                                        <TextInput
                                                                                                                                                                                                                                                                                                                                                                                                                                                    style={styles.input}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                placeholder="License Plate"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            value={licensePlate}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onChangeText={setLicensePlate}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <TextInput
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={styles.input}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      placeholder="Password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              secureTextEntry
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      value={password}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onChangeText={setPassword}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <TextInput
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  style={styles.input}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          placeholder="Confirm Password"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  secureTextEntry
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          value={confirmPassword}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  onChangeText={setConfirmPassword}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Button title="Register" onPress={handleRegister} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <Text style={styles.link} onPress={() => navigation.navigate('Login')}>Already have an account? Login</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            container: { flex: 1, padding: 20, justifyContent: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              title: { fontSize: 24, textAlign: 'center', marginBottom: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                input: { borderWidth: 1, padding: 10, marginVertical: 8, borderRadius: 6 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  toggleContainer: { flexDirection: 'row', justifyContent: 'center', marginBottom: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    toggle: { padding: 10, marginHorizontal: 10, backgroundColor: '#ccc', borderRadius: 6 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      active: { backgroundColor: '#4CAF50' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        link: { textAlign: 'center', marginTop: 15, color: 'blue' }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        export default RegisterScreen;