import React, { useState } from 'react';
import { View, Text, StyleSheet, Button } from 'react-native';
import { Picker } from '@react-native-picker/picker';
import { useNavigation } from '@react-navigation/native';

const cities = ['Lilongwe', 'Blantyre', 'Mzuzu', 'Zomba', 'Mangochi'];

const SelectCityScreen = () => {
  const [selectedCity, setSelectedCity] = useState('');
    const [fromCity, setFromCity] = useState('');
      const [toCity, setToCity] = useState('');
        const [isIntercity, setIsIntercity] = useState(false);

          const navigation = useNavigation();

            const handleProceed = () => {
                if (isIntercity) {
                      if (fromCity && toCity) {
                              navigation.navigate('TaxiType', { fromCity, toCity, intercity: true });
                                    } else {
                                            alert('Please select both cities');
                                                  }
                                                      } else {
                                                            if (selectedCity) {
                                                                    navigation.navigate('TaxiType', { selectedCity, intercity: false });
                                                                          } else {
                                                                                  alert('Please select a city');
                                                                                        }
                                                                                            }
                                                                                              };

                                                                                                return (
                                                                                                    <View style={styles.container}>
                                                                                                          <Text style={styles.label}>Travel Type:</Text>
                                                                                                                <Picker
                                                                                                                        selectedValue={isIntercity ? 'intercity' : 'local'}
                                                                                                                                onValueChange={(value) => setIsIntercity(value === 'intercity')}
                                                                                                                                        style={styles.picker}
                                                                                                                                              >
                                                                                                                                                      <Picker.Item label="Local City Travel" value="local" />
                                                                                                                                                              <Picker.Item label="Intercity Travel" value="intercity" />
                                                                                                                                                                    </Picker>

                                                                                                                                                                          {isIntercity ? (
                                                                                                                                                                                  <>
                                                                                                                                                                                            <Text style={styles.label}>From:</Text>
                                                                                                                                                                                                      <Picker
                                                                                                                                                                                                                  selectedValue={fromCity}
                                                                                                                                                                                                                              onValueChange={setFromCity}
                                                                                                                                                                                                                                          style={styles.picker}
                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                <Picker.Item label="Select starting city" value="" />
                                                                                                                                                                                                                                                                            {cities.map((city) => (
                                                                                                                                                                                                                                                                                          <Picker.Item key={city} label={city} value={city} />
                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                </Picker>

                                                                                                                                                                                                                                                                                                                          <Text style={styles.label}>To:</Text>
                                                                                                                                                                                                                                                                                                                                    <Picker
                                                                                                                                                                                                                                                                                                                                                selectedValue={toCity}
                                                                                                                                                                                                                                                                                                                                                            onValueChange={setToCity}
                                                                                                                                                                                                                                                                                                                                                                        style={styles.picker}
                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                              <Picker.Item label="Select destination city" value="" />
                                                                                                                                                                                                                                                                                                                                                                                                          {cities.map((city) => (
                                                                                                                                                                                                                                                                                                                                                                                                                        <Picker.Item key={city} label={city} value={city} />
                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                              </Picker>
                                                                                                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Text style={styles.label}>Select City:</Text>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <Picker
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    selectedValue={selectedCity}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                onValueChange={setSelectedCity}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            style={styles.picker}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Picker.Item label="Choose your city" value="" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {cities.map((city) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <Picker.Item key={city} label={city} value={city} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </Picker>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <View style={styles.buttonContainer}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <Button title="Proceed" onPress={handleProceed} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </View>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const styles = StyleSheet.create({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            container: { flex: 1, padding: 20, justifyContent: 'center' },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              label: { fontSize: 18, marginBottom: 5 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                picker: { height: 50, marginBottom: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  buttonContainer: { marginTop: 20 },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  export default SelectCityScreen;